---
- name: Run configuration backup
  cisco.ios.ios_config:
    backup: true
    backup_options:
      filename: "{{ inventory_hostname }}_pre-config.txt"
      dir_path: "/tmp/semaphore/pyats/backup_config"
