---
name: ospf-config-change
on:
  push:
    branches:
      - main
jobs:
  apply-change:
    runs-on: webhook-runner
    steps:
      - shell: sh
        run: |
          apk add --no-cache curl
          curl -k -X POST http://192.168.50.64:3333/api/integrations/lj3wmph16gd50mrm \
          -u "ahmad:ahmad1234"
