name: ospf-config-change
on:
  push:
    branches:
      - main
jobs:
  backup:
    runs-on: webhook-runner
    steps:
      - run: |
          curl -k -X POST http://192.168.50.64:3333/api/integrations/bclt0pj4tecvs2ii \
          -u "ahmad:ahmad1234"
  capture_before_state:
    needs: backup
    runs-on: webhook-runner
    steps:
      - run: |
          curl -k -X POST http://192.168.50.64:3000/api/integrations/wti2t7zhuwzywolp \
          -u "ahmad:ahmad1234" \
          -H "Content-Type: application/json" \
          -d '{
            "param1": "pre-change"
          }'
  apply-change:
    needs: capture_before_state
    runs-on: webhook-runner
    steps:
      - run: |
          curl -k -X POST http://192.168.50.64:3000/api/integrations/lj3wmph16gd50mrm \
          -u "ahmad:ahmad1234"
  capture_after_state:
    needs: apply-change
    runs-on: webhook-runner
    steps:
      - run: |
          curl -k -X POST http://192.168.50.64:3000/api/integrations/wti2t7zhuwzywolp \
          -u "ahmad:ahmad1234" \
          -H "Content-Type: application/json" \
          -d '{
            "param1": "post-change"
          }'
  validate:
    needs: ['apply-change', 'capture_after_state', 'capture_before_state']
    runs-on: webhook-runner
    steps:
      - run: |
          curl -k -X POST http://192.168.50.64:3000/api/integrations/936nnwta92r7um5u \
          -u "ahmad:ahmad1234" \
          -H "Content-Type: application/json" \
          -d '{
            "param1": "post-change"
          }'
  rollback:
    needs: validate
    if: failure()
    runs-on: webhook-runner
    steps:
      - run: |
          curl -k -X POST http://192.168.50.64:3000/api/integrations/19w3ogmfjnpy7d9y \
          -u "ahmad:ahmad1234"